import { useEffect,useState } from "react";
import { BookOpen,Pencil,Plus,Search,Trash2 } from "lucide-react";
import { motion } from "framer-motion";
import { useDispatch,useSelector } from "react-redux";
import { useCreateCourseMutation,useDeleteCourseMutation,useGetCoursesQuery,useUpdateCourseMutation } from "../store/api";
import { showToast } from "../store/slices/uiSlice";
import PageHeader from "../components/PageHeader";
import Modal from "../components/Modal";
import Field from "../components/Field";
import EmptyState from "../components/EmptyState";
import { money } from "../utils/format";

const initial={title:"",code:"",duration:"",fee:"",capacity:30,description:"",active:true};

export default function Courses(){
  const {user}=useSelector(s=>s.auth),dispatch=useDispatch();
  const [search,setSearch]=useState(""),[page,setPage]=useState(1),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(initial);
  const {data,isLoading,error}=useGetCoursesQuery({search,page,limit:8});const [create]=useCreateCourseMutation(),[update]=useUpdateCourseMutation(),[remove]=useDeleteCourseMutation();
  useEffect(()=>setPage(1),[search]);
  async function save(e){e.preventDefault();try{const p={...form,fee:Number(form.fee),capacity:Number(form.capacity)};if(editing)await update({id:editing._id,...p}).unwrap();else await create(p).unwrap();setOpen(false);dispatch(showToast({type:"success",message:editing?"Course updated.":"Course created."}))}catch(err){dispatch(showToast({type:"error",message:err?.data?.message||"Unable to save course."}))}}
  async function del(id){if(!confirm("Delete this course?"))return;try{await remove(id).unwrap();dispatch(showToast({type:"success",message:"Course deleted."}))}catch(err){dispatch(showToast({type:"error",message:err?.data?.message||"Unable to delete course."}))}}
  return <div className="space-y-5"><PageHeader eyebrow="Education" title="Courses" description="Manage your training and course catalogue." action={<button className="btn-primary" onClick={()=>{setEditing(null);setForm(initial);setOpen(true)}}><Plus size={17}/> Add course</button>}/>
    <div className="card overflow-hidden"><div className="border-b border-slate-100 p-4"><div className="relative max-w-xl"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="field pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search course title or code..."/></div></div>
      {error?<div className="m-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error.data?.message||"Unable to load courses."}</div>:isLoading?<Skeleton/>:data?.courses?.length?<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Course</th><th className="px-5 py-3">Code</th><th className="px-5 py-3">Duration</th><th className="px-5 py-3">Fee</th><th className="px-5 py-3">Capacity</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{data.courses.map((c,i)=><motion.tr key={c._id} initial={{opacity:0}} animate={{opacity:1}} transition={{delay:i*.02}} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-semibold">{c.title}</p><p className="max-w-sm truncate text-xs text-slate-400">{c.description||"No description"}</p></td><td className="px-5 py-4 font-semibold">{c.code}</td><td className="px-5 py-4 text-slate-600">{c.duration}</td><td className="px-5 py-4 font-semibold">{money(c.fee)}</td><td className="px-5 py-4 text-slate-600">{c.capacity}</td><td className="px-5 py-4"><span className={`badge ${c.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{c.active?"active":"inactive"}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-1">{<><button className="icon-btn" onClick={()=>{setEditing(c);setForm({title:c.title,code:c.code,duration:c.duration,fee:c.fee,capacity:c.capacity,description:c.description||"",active:Boolean(c.active)});setOpen(true)}}><Pencil size={16}/></button><button className="icon-btn text-red-500 hover:bg-red-50" onClick={()=>del(c._id)}><Trash2 size={16}/></button></>}</div></td></motion.tr>)}</tbody></table></div>:<EmptyState icon={BookOpen} title="No courses found." text="Create your first course to begin."/>}
      <Pagination pagination={data?.pagination} onChange={setPage}/>
    </div>
    <Modal open={open} onClose={()=>setOpen(false)} title={editing?"Edit course":"Add course"}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Field label="Course title" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><Field label="Course code" required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><Field label="Duration" required value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/><Field label="Fee (₹)" type="number" min="0" required value={form.fee} onChange={e=>setForm({...form,fee:e.target.value})}/><Field label="Capacity" type="number" min="1" required value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/><label><span className="label">Active</span><select className="field" value={String(form.active)} onChange={e=>setForm({...form,active:e.target.value==="true"})}><option value="true">Yes</option><option value="false">No</option></select></label><div className="sm:col-span-2"><label className="label">Description</label><textarea className="field min-h-24" value={form.description||""} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="sm:col-span-2"><button className="btn-primary w-full">{editing?"Update course":"Create course"}</button></div></form></Modal>
  </div>
}
function Pagination({pagination,onChange}){if(!pagination||pagination.pages<=1)return null;return <div className="flex items-center justify-between border-t border-slate-100 p-4 text-sm"><span>Page {pagination.page} of {pagination.pages}</span><div className="flex gap-2"><button className="btn-secondary" disabled={pagination.page<=1} onClick={()=>onChange(pagination.page-1)}>Previous</button><button className="btn-secondary" disabled={pagination.page>=pagination.pages} onClick={()=>onChange(pagination.page+1)}>Next</button></div></div>}
function Skeleton(){return <div className="space-y-3 p-5">{Array.from({length:6}).map((_,i)=><div className="h-14 animate-pulse rounded-xl bg-slate-100" key={i}/>)}</div>}
