import { useEffect,useState } from "react";
import { CreditCard, Eye, Pencil, Plus, Search, Trash2, Users } from "lucide-react";
import { motion } from "framer-motion";
import { useDispatch,useSelector } from "react-redux";
import PageHeader from "../components/PageHeader";
import Modal from "../components/Modal";
import Field from "../components/Field";
import EmptyState from "../components/EmptyState";
import PaySalaryModal from "../components/PaySalaryModal";
import { useCreateEmployeeMutation,useDeleteEmployeeMutation,useGetEmployeesQuery,useUpdateEmployeeMutation } from "../store/api";
import { showToast } from "../store/slices/uiSlice";
import { money,dateText } from "../utils/format";

const initial={name:"",email:"",phone:"",department:"",position:"",salary:"",status:"active",joiningDate:""};

export default function Employees(){
  const {user}=useSelector(s=>s.auth),dispatch=useDispatch();
  const [search,setSearch]=useState(""),[page,setPage]=useState(1),[open,setOpen]=useState(false),[payOpen,setPayOpen]=useState(false),[payEmployee,setPayEmployee]=useState(null),[editing,setEditing]=useState(null),[form,setForm]=useState(initial);
  const {data,isLoading,error}=useGetEmployeesQuery({search,page,limit:8});
  const [create,{isLoading:createBusy}]=useCreateEmployeeMutation(),[update,{isLoading:updateBusy}]=useUpdateEmployeeMutation(),[remove]=useDeleteEmployeeMutation();
  useEffect(()=>setPage(1),[search]);
  function edit(e){setEditing(e);setForm({name:e.name,email:e.email,phone:e.phone||"",department:e.department,position:e.position,salary:e.salary,status:e.status,joiningDate:e.joiningDate?e.joiningDate.slice(0,10):""});setOpen(true)}
  async function save(ev){ev.preventDefault();try{const p={...form,salary:Number(form.salary),joiningDate:form.joiningDate||undefined};if(editing)await update({id:editing._id,...p}).unwrap();else await create(p).unwrap();setOpen(false);dispatch(showToast({type:"success",message:editing?"Employee updated.":"Employee created."}))}catch(err){dispatch(showToast({type:"error",message:err?.data?.message||"Unable to save employee."}))}}
  async function del(id){if(!confirm("Delete this employee?"))return;try{await remove(id).unwrap();dispatch(showToast({type:"success",message:"Employee deleted."}))}catch(err){dispatch(showToast({type:"error",message:err?.data?.message||"Unable to delete employee."}))}}
  return <div className="space-y-5"><PageHeader eyebrow="People" title="Employees" description="Manage employee records, salaries and monthly payment history." action={user?.role!=="staff"&&<button className="btn-primary" onClick={()=>{setEditing(null);setForm(initial);setOpen(true)}}><Plus size={17}/> Add employee</button>}/>
    <div className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 md:flex-row md:items-center"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="field pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name, email, employee ID or position..."/></div><span className="text-xs text-slate-400">{data?.pagination?.total||0} records</span></div>
      {error?<div className="m-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error.data?.message||"Unable to load employees."}</div>:isLoading?<Skeleton/>:data?.employees?.length?<div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Department</th><th className="px-5 py-3">Position</th><th className="px-5 py-3">Salary</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{data.employees.map((e,i)=><motion.tr key={e._id} initial={{opacity:0}} animate={{opacity:1}} transition={{delay:i*.025}} className="hover:bg-slate-50"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-indigo-50 text-xs font-black text-indigo-600">{e.name.slice(0,2).toUpperCase()}</div><div><p className="font-semibold">{e.name}</p><p className="text-xs text-slate-400">{e.employeeId} · {e.email}</p></div></div></td><td className="px-5 py-4 text-slate-600">{e.department}</td><td className="px-5 py-4 text-slate-600">{e.position}</td><td className="px-5 py-4 font-semibold">{money(e.salary)}<span className="text-xs font-normal text-slate-400"> /mo</span></td><td className="px-5 py-4"><span className={`badge ${e.status==="active"?"bg-emerald-50 text-emerald-700":e.status==="on-leave"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-600"}`}>{e.status}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-1">{user?.role==="admin"&&<button title="Pay salary" className="icon-btn text-emerald-600 hover:bg-emerald-50" onClick={()=>{setPayEmployee(e);setPayOpen(true)}}><CreditCard size={16}/></button>}<button title="View" className="icon-btn" onClick={()=>alert(`Employee: ${e.name}\nJoined: ${dateText(e.joiningDate)}\nPhone: ${e.phone||"—"}`)}><Eye size={16}/></button>{user?.role!=="staff"&&<button title="Edit" className="icon-btn" onClick={()=>edit(e)}><Pencil size={16}/></button>}{user?.role==="admin"&&<button title="Delete" className="icon-btn text-red-500 hover:bg-red-50" onClick={()=>del(e._id)}><Trash2 size={16}/></button>}</div></td></motion.tr>)}</tbody></table></div>:<EmptyState icon={Users} title="No employees found." text="Add an employee to start managing payroll."/>}
      <Pagination pagination={data?.pagination} onChange={setPage}/></div>
    <Modal open={open} onClose={()=>setOpen(false)} title={editing?"Edit employee":"Add employee"}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Field label="Full name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field label="Email" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Field label="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><Field label="Department" required value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/><Field label="Position" required value={form.position} onChange={e=>setForm({...form,position:e.target.value})}/><Field label="Monthly salary (₹)" type="number" min="0" required value={form.salary} onChange={e=>setForm({...form,salary:e.target.value})}/><Field label="Joining date" type="date" value={form.joiningDate} onChange={e=>setForm({...form,joiningDate:e.target.value})}/><label><span className="label">Status</span><select className="field" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option><option value="on-leave">On leave</option></select></label><div className="sm:col-span-2"><button disabled={createBusy||updateBusy} className="btn-primary w-full">{createBusy||updateBusy?"Saving…":editing?"Update employee":"Create employee"}</button></div></form></Modal>
    <PaySalaryModal employee={payEmployee} open={payOpen} onClose={()=>{setPayOpen(false);setPayEmployee(null)}}/>
  </div>
}
function Pagination({pagination,onChange}){if(!pagination||pagination.pages<=1)return null;return <div className="flex items-center justify-between border-t border-slate-100 p-4 text-sm"><span>Page {pagination.page} of {pagination.pages}</span><div className="flex gap-2"><button className="btn-secondary" disabled={pagination.page<=1} onClick={()=>onChange(pagination.page-1)}>Previous</button><button className="btn-secondary" disabled={pagination.page>=pagination.pages} onClick={()=>onChange(pagination.page+1)}>Next</button></div></div>}
function Skeleton(){return <div className="space-y-3 p-5">{Array.from({length:6}).map((_,i)=><div className="h-14 animate-pulse rounded-xl bg-slate-100" key={i}/>)}</div>}
