import { useEffect,useState } from "react";
import { Package,Pencil,Plus,Search,Trash2 } from "lucide-react";
import { motion } from "framer-motion";
import { useDispatch,useSelector } from "react-redux";
import { useCreateProductMutation,useDeleteProductMutation,useGetProductsQuery,useUpdateProductMutation } from "../store/api";
import { showToast } from "../store/slices/uiSlice";
import PageHeader from "../components/PageHeader";
import Modal from "../components/Modal";
import Field from "../components/Field";
import EmptyState from "../components/EmptyState";
import { money } from "../utils/format";

const initial={name:"",sku:"",category:"",price:"",quantity:"",supplier:"",lowStockThreshold:5};

export default function Products(){
  const {user}=useSelector(s=>s.auth),dispatch=useDispatch();
  const [search,setSearch]=useState(""),[page,setPage]=useState(1),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(initial);
  const {data,isLoading,error}=useGetProductsQuery({search,page,limit:8});const [create]=useCreateProductMutation(),[update]=useUpdateProductMutation(),[remove]=useDeleteProductMutation();
  useEffect(()=>setPage(1),[search]);
  async function save(e){e.preventDefault();try{const p={...form,price:Number(form.price),quantity:Number(form.quantity),lowStockThreshold:Number(form.lowStockThreshold)};if(editing)await update({id:editing._id,...p}).unwrap();else await create(p).unwrap();setOpen(false);dispatch(showToast({type:"success",message:editing?"Product updated.":"Product created."}))}catch(err){dispatch(showToast({type:"error",message:err?.data?.message||"Unable to save product."}))}}
  async function del(id){if(!confirm("Delete this product?"))return;try{await remove(id).unwrap();dispatch(showToast({type:"success",message:"Product deleted."}))}catch(err){dispatch(showToast({type:"error",message:err?.data?.message||"Unable to delete product."}))}}
  return <div className="space-y-5"><PageHeader eyebrow="Operations" title="Products" description="Manage stock and inventory value." action={user?.role!=="staff"&&<button className="btn-primary" onClick={()=>{setEditing(null);setForm(initial);setOpen(true)}}><Plus size={17}/> Add product</button>}/><div className="card overflow-hidden"><div className="border-b border-slate-100 p-4"><div className="relative max-w-xl"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="field pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search product, SKU or supplier..."/></div></div>
  {error?<div className="m-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error.data?.message||"Unable to load products."}</div>:isLoading?<Skeleton/>:data?.products?.length?<div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Product</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Price</th><th className="px-5 py-3">Stock</th><th className="px-5 py-3">Value</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{data.products.map((p,i)=>{const low=p.quantity<=p.lowStockThreshold;return <motion.tr key={p._id} initial={{opacity:0}} animate={{opacity:1}} transition={{delay:i*.02}} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-semibold">{p.name}</p><p className="text-xs text-slate-400">{p.sku} · {p.supplier||"No supplier"}</p></td><td className="px-5 py-4 text-slate-600">{p.category}</td><td className="px-5 py-4 font-semibold">{money(p.price)}</td><td className="px-5 py-4"><span className={`badge ${low?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{p.quantity} {low?"· low":"· in stock"}</span></td><td className="px-5 py-4 font-semibold">{money(p.price*p.quantity)}</td><td className="px-5 py-4"><div className="flex justify-end gap-1">{user?.role!=="staff"&&<button className="icon-btn" onClick={()=>{setEditing(p);setForm({name:p.name,sku:p.sku,category:p.category,price:p.price,quantity:p.quantity,supplier:p.supplier||"",lowStockThreshold:p.lowStockThreshold});setOpen(true)}}><Pencil size={16}/></button>}{user?.role==="admin"&&<button className="icon-btn text-red-500 hover:bg-red-50" onClick={()=>del(p._id)}><Trash2 size={16}/></button>}</div></td></motion.tr>})}</tbody></table></div>:<EmptyState icon={Package} title="No products found." text="Create your first product to track inventory."/>}<Pagination pagination={data?.pagination} onChange={setPage}/></div>
  <Modal open={open} onClose={()=>setOpen(false)} title={editing?"Edit product":"Add product"}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Field label="Product name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field label="SKU" required value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/><Field label="Category" required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><Field label="Supplier" value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})}/><Field label="Price (₹)" type="number" min="0" step="0.01" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><Field label="Quantity" type="number" min="0" required value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><Field label="Low-stock threshold" type="number" min="0" required value={form.lowStockThreshold} onChange={e=>setForm({...form,lowStockThreshold:e.target.value})}/><div className="sm:col-span-2"><button className="btn-primary w-full">{editing?"Update product":"Create product"}</button></div></form></Modal></div>
}
function Pagination({pagination,onChange}){if(!pagination||pagination.pages<=1)return null;return <div className="flex items-center justify-between border-t border-slate-100 p-4 text-sm"><span>Page {pagination.page} of {pagination.pages}</span><div className="flex gap-2"><button className="btn-secondary" disabled={pagination.page<=1} onClick={()=>onChange(pagination.page-1)}>Previous</button><button className="btn-secondary" disabled={pagination.page>=pagination.pages} onClick={()=>onChange(pagination.page+1)}>Next</button></div></div>}
function Skeleton(){return <div className="space-y-3 p-5">{Array.from({length:6}).map((_,i)=><div className="h-14 animate-pulse rounded-xl bg-slate-100" key={i}/>)}</div>}
