import { useEffect,useState } from "react";
import { Building2,LockKeyhole,Pencil,Plus,Search,Trash2 } from "lucide-react";
import { motion } from "framer-motion";
import { useDispatch,useSelector } from "react-redux";
import { useCreateSchoolMutation,useDeleteSchoolMutation,useGetSchoolsQuery,useUpdateSchoolMutation } from "../store/api";
import { showToast } from "../store/slices/uiSlice";
import PageHeader from "../components/PageHeader";
import Modal from "../components/Modal";
import Field from "../components/Field";
import EmptyState from "../components/EmptyState";

const initial={name:"",code:"",address:"",phone:"",email:"",principal:"",status:"active"};

export default function Schools(){
  const {user}=useSelector(s=>s.auth),dispatch=useDispatch();
  const [search,setSearch]=useState(""),[page,setPage]=useState(1),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(initial);
  const {data,isLoading,error}=useGetSchoolsQuery({search,page,limit:8});const [create]=useCreateSchoolMutation(),[update]=useUpdateSchoolMutation(),[remove]=useDeleteSchoolMutation();
  useEffect(()=>setPage(1),[search]);
  async function save(e){e.preventDefault();try{if(editing)await update({id:editing._id,...form}).unwrap();else await create(form).unwrap();setOpen(false);dispatch(showToast({type:"success",message:editing?"School updated.":"School created."}))}catch(err){dispatch(showToast({type:"error",message:err?.data?.message||"Unable to save school."}))}}
  async function del(id){if(!confirm("Delete this school?"))return;try{await remove(id).unwrap();dispatch(showToast({type:"success",message:"School deleted."}))}catch(err){dispatch(showToast({type:"error",message:err?.data?.message||"Unable to delete school."}))}}
  return <div className="space-y-5"><PageHeader eyebrow="Education" title="Schools" description="Manage the schools and institutes in your organization." action={user?.role==="admin"?<button className="btn-primary" onClick={()=>{setEditing(null);setForm(initial);setOpen(true)}}><Plus size={17}/> Add school</button>:<button className="btn-secondary" disabled title="Admin permission required"><LockKeyhole size={16}/> Add school</button>}/>
    <div className="card overflow-hidden"><div className="border-b border-slate-100 p-4"><div className="relative max-w-xl"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="field pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search school, code or principal..."/></div></div>
      {error?<div className="m-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error.data?.message||"Unable to load schools."}</div>:isLoading?<Skeleton/>:data?.schools?.length?<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">School</th><th className="px-5 py-3">Code</th><th className="px-5 py-3">Principal</th><th className="px-5 py-3">Contact</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{data.schools.map((s,i)=><motion.tr key={s._id} initial={{opacity:0}} animate={{opacity:1}} transition={{delay:i*.02}} className="hover:bg-slate-50"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Building2 size={18}/></div><div><p className="font-semibold">{s.name}</p><p className="max-w-sm truncate text-xs text-slate-400">{s.address}</p></div></div></td><td className="px-5 py-4 font-semibold">{s.code}</td><td className="px-5 py-4 text-slate-600">{s.principal||"—"}</td><td className="px-5 py-4 text-slate-600">{s.email||s.phone||"—"}</td><td className="px-5 py-4"><span className={`badge ${s.status==="active"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{s.status}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-1">{user?.role==="admin"&&<><button className="icon-btn" onClick={()=>{setEditing(s);setForm({name:s.name,code:s.code,address:s.address,phone:s.phone||"",email:s.email||"",principal:s.principal||"",status:s.status});setOpen(true)}}><Pencil size={16}/></button><button className="icon-btn text-red-500 hover:bg-red-50" onClick={()=>del(s._id)}><Trash2 size={16}/></button></>}</div></td></motion.tr>)}</tbody></table></div>:<EmptyState icon={Building2} title="No schools found." text="Create your first school to begin."/>}
      <Pagination pagination={data?.pagination} onChange={setPage}/>
    </div>
    <Modal open={open} onClose={()=>setOpen(false)} title={editing?"Edit school":"Add school"}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Field label="School name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field label="School code" required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><Field label="Principal" value={form.principal} onChange={e=>setForm({...form,principal:e.target.value})}/><Field label="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><Field label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><label><span className="label">Status</span><select className="field" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><div className="sm:col-span-2"><label className="label">Address</label><textarea className="field min-h-24" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div><div className="sm:col-span-2"><button className="btn-primary w-full">{editing?"Update school":"Create school"}</button></div></form></Modal>
  </div>
}
function Pagination({pagination,onChange}){if(!pagination||pagination.pages<=1)return null;return <div className="flex items-center justify-between border-t border-slate-100 p-4 text-sm"><span>Page {pagination.page} of {pagination.pages}</span><div className="flex gap-2"><button className="btn-secondary" disabled={pagination.page<=1} onClick={()=>onChange(pagination.page-1)}>Previous</button><button className="btn-secondary" disabled={pagination.page>=pagination.pages} onClick={()=>onChange(pagination.page+1)}>Next</button></div></div>}
function Skeleton(){return <div className="space-y-3 p-5">{Array.from({length:6}).map((_,i)=><div className="h-14 animate-pulse rounded-xl bg-slate-100" key={i}/>)}</div>}
