import { useEffect,useState } from "react";
import { GraduationCap,Pencil,Plus,Search,Trash2 } from "lucide-react";
import { motion } from "framer-motion";
import { useDispatch,useSelector } from "react-redux";
import { useCreateStudentMutation,useDeleteStudentMutation,useGetCoursesQuery,useGetSchoolsQuery,useGetStudentsQuery,useUpdateStudentMutation } from "../store/api";
import { showToast } from "../store/slices/uiSlice";
import PageHeader from "../components/PageHeader";
import Modal from "../components/Modal";
import Field from "../components/Field";
import EmptyState from "../components/EmptyState";
import { money } from "../utils/format";

const initial={name:"",email:"",phone:"",school:"",course:"",enrollmentStatus:"active",totalFee:""};

export default function Students(){
  const {user}=useSelector(s=>s.auth),dispatch=useDispatch();
  const [search,setSearch]=useState(""),[page,setPage]=useState(1),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(initial);
  const {data,isLoading,error}=useGetStudentsQuery({search,page,limit:8});
  const {data:schools}=useGetSchoolsQuery({search:"",page:1,limit:100});
  const {data:courses}=useGetCoursesQuery({search:"",page:1,limit:100});
  const [create]=useCreateStudentMutation(),[update]=useUpdateStudentMutation(),[remove]=useDeleteStudentMutation();
  useEffect(()=>setPage(1),[search]);
  async function save(e){e.preventDefault();try{const p={...form,totalFee:Number(form.totalFee)};if(editing)await update({id:editing._id,...p}).unwrap();else await create(p).unwrap();setOpen(false);dispatch(showToast({type:"success",message:editing?"Student updated.":"Student created."}))}catch(err){dispatch(showToast({type:"error",message:err?.data?.message||"Unable to save student."}))}}
  function edit(s){setEditing(s);setForm({name:s.name,email:s.email||"",phone:s.phone||"",school:s.school?._id||"",course:s.course?._id||"",enrollmentStatus:s.enrollmentStatus,totalFee:s.totalFee||""});setOpen(true)}
  async function del(id){if(!confirm("Delete this student?"))return;try{await remove(id).unwrap();dispatch(showToast({type:"success",message:"Student deleted."}))}catch(err){dispatch(showToast({type:"error",message:err?.data?.message||"Unable to delete student."}))}}
  return <div className="space-y-5"><PageHeader eyebrow="Education" title="Students" description="Track enrollments across schools and courses." action={<button className="btn-primary" onClick={()=>{setEditing(null);setForm(initial);setOpen(true)}}><Plus size={17}/> Add student</button>}/>
    <div className="card overflow-hidden"><div className="border-b border-slate-100 p-4"><div className="relative max-w-xl"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input className="field pl-10" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search student name, email or ID..."/></div></div>
      {error?<div className="m-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error.data?.message||"Unable to load students."}</div>:isLoading?<Skeleton/>:data?.students?.length?<div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">School</th><th className="px-5 py-3">Course</th><th className="px-5 py-3">Fee</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{data.students.map((s,i)=><motion.tr key={s._id} initial={{opacity:0}} animate={{opacity:1}} transition={{delay:i*.02}} className="hover:bg-slate-50"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-cyan-50 text-xs font-black text-cyan-700">{s.name.slice(0,2).toUpperCase()}</div><div><p className="font-semibold">{s.name}</p><p className="text-xs text-slate-400">{s.studentId} · {s.email||"No email"}</p></div></div></td><td className="px-5 py-4"><p className="font-medium">{s.school?.name||"—"}</p><p className="text-xs text-slate-400">{s.school?.code}</p></td><td className="px-5 py-4"><p className="font-medium">{s.course?.title||"—"}</p><p className="text-xs text-slate-400">{s.course?.code}</p></td><td className="px-5 py-4 font-semibold">{money(s.totalFee)}</td><td className="px-5 py-4"><span className={`badge ${s.enrollmentStatus==="active"?"bg-emerald-50 text-emerald-700":s.enrollmentStatus==="completed"?"bg-indigo-50 text-indigo-700":"bg-slate-100 text-slate-600"}`}>{s.enrollmentStatus}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-1">{<><button className="icon-btn" onClick={()=>edit(s)}><Pencil size={16}/></button><button className="icon-btn text-red-500 hover:bg-red-50" onClick={()=>del(s._id)}><Trash2 size={16}/></button></>}</div></td></motion.tr>)}</tbody></table></div>:<EmptyState icon={GraduationCap} title="No students found." text="Create your first student to begin."/>}
      <Pagination pagination={data?.pagination} onChange={setPage}/>
    </div>
    <Modal open={open} onClose={()=>setOpen(false)} title={editing?"Edit student":"Add student"}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Field label="Student name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Field label="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><Field label="Total fee (₹)" type="number" min="0" value={form.totalFee} onChange={e=>setForm({...form,totalFee:e.target.value})}/><label><span className="label">School</span><select required className="field" value={form.school} onChange={e=>setForm({...form,school:e.target.value})}><option value="">Select school</option>{schools?.schools?.map(s=><option key={s._id} value={s._id}>{s.name}</option>)}</select></label><label><span className="label">Course</span><select required className="field" value={form.course} onChange={e=>setForm({...form,course:e.target.value})}><option value="">Select course</option>{courses?.courses?.map(c=><option key={c._id} value={c._id}>{c.title}</option>)}</select></label><label><span className="label">Enrollment status</span><select className="field" value={form.enrollmentStatus} onChange={e=>setForm({...form,enrollmentStatus:e.target.value})}><option value="active">Active</option><option value="completed">Completed</option><option value="paused">Paused</option><option value="dropped">Dropped</option></select></label><div className="sm:col-span-2"><button className="btn-primary w-full">{editing?"Update student":"Create student"}</button></div></form></Modal>
  </div>
}
function Pagination({pagination,onChange}){if(!pagination||pagination.pages<=1)return null;return <div className="flex items-center justify-between border-t border-slate-100 p-4 text-sm"><span>Page {pagination.page} of {pagination.pages}</span><div className="flex gap-2"><button className="btn-secondary" disabled={pagination.page<=1} onClick={()=>onChange(pagination.page-1)}>Previous</button><button className="btn-secondary" disabled={pagination.page>=pagination.pages} onClick={()=>onChange(pagination.page+1)}>Next</button></div></div>}
function Skeleton(){return <div className="space-y-3 p-5">{Array.from({length:6}).map((_,i)=><div className="h-14 animate-pulse rounded-xl bg-slate-100" key={i}/>)}</div>}
